apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: heartnest-web
  namespace: ns-i61rahoe
  labels:
    app.kubernetes.io/name: heartnest-web
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
